//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_CIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD2
    {
        public decimal ac_id { get; set; }
        public Nullable<decimal> cu_id { get; set; }
        public Nullable<int> ac_code { get; set; }
        public string ac_name { get; set; }
        public Nullable<int> ac_daytotal { get; set; }
        public string ac_timetable { get; set; }
        public string ac_timetable1 { get; set; }
    
        public virtual CURSO2 CURSO2 { get; set; }
    }
}
