//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_CIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public decimal acti_id { get; set; }
        public decimal muni_id { get; set; }
        public decimal cu_id { get; set; }
        public string acti_name { get; set; }
        public Nullable<int> acti_datytotal { get; set; }
        public Nullable<System.DateTime> acti_startDate { get; set; }
        public Nullable<System.DateTime> acti_endDate { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
