//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_CIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSO2()
        {
            this.ACTIVIDAD2 = new HashSet<ACTIVIDAD2>();
        }
    
        public decimal cu_id { get; set; }
        public Nullable<int> cu_code { get; set; }
        public string cu_name { get; set; }
        public Nullable<int> cu_duration { get; set; }
        public Nullable<System.DateTime> cu_startDate { get; set; }
        public Nullable<System.DateTime> cu_endDate { get; set; }
        public string cu_note { get; set; }
        public string cu_days { get; set; }
        public string am_name { get; set; }
        public string lo_name { get; set; }
        public string pf_name { get; set; }
        public Nullable<double> pf_version { get; set; }
        public string pe_name { get; set; }
        public Nullable<decimal> so_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDAD2> ACTIVIDAD2 { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
