//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_CIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public decimal curso_id { get; set; }
        public string curso_name { get; set; }
        public Nullable<int> curso_code { get; set; }
        public Nullable<double> curso_version { get; set; }
        public string curso_programa { get; set; }
        public Nullable<int> curso_duration { get; set; }
        public Nullable<System.DateTime> curso_startDate { get; set; }
        public Nullable<System.DateTime> curso_endDate { get; set; }
        public string curso_note { get; set; }
        public string curso_days { get; set; }
        public decimal muni_id { get; set; }
        public decimal pe_id { get; set; }
        public decimal soli_id { get; set; }
    
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual PROGRAMA_ESPECIAL PROGRAMA_ESPECIAL { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
