//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC_CIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FC_CIP_BDEntities : DbContext
    {
        public FC_CIP_BDEntities()
            : base("name=FC_CIP_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual DbSet<COORDINADOR> COORDINADOR { get; set; }
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<INSTRUCTOR> INSTRUCTOR { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual DbSet<PROGRAMA_ESPECIAL> PROGRAMA_ESPECIAL { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUD { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual ObjectResult<getSolicitudes_Result> getSolicitudes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSolicitudes_Result>("getSolicitudes");
        }
    
        public virtual ObjectResult<getSolicitudesID_Result> getSolicitudesID(Nullable<decimal> so_id)
        {
            var so_idParameter = so_id.HasValue ?
                new ObjectParameter("so_id", so_id) :
                new ObjectParameter("so_id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSolicitudesID_Result>("getSolicitudesID", so_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> RegistrarUsuario(Nullable<decimal> us_nid, string us_password, string us_name, string us_lastname, string us_email, Nullable<decimal> us_phone)
        {
            var us_nidParameter = us_nid.HasValue ?
                new ObjectParameter("us_nid", us_nid) :
                new ObjectParameter("us_nid", typeof(decimal));
    
            var us_passwordParameter = us_password != null ?
                new ObjectParameter("us_password", us_password) :
                new ObjectParameter("us_password", typeof(string));
    
            var us_nameParameter = us_name != null ?
                new ObjectParameter("us_name", us_name) :
                new ObjectParameter("us_name", typeof(string));
    
            var us_lastnameParameter = us_lastname != null ?
                new ObjectParameter("us_lastname", us_lastname) :
                new ObjectParameter("us_lastname", typeof(string));
    
            var us_emailParameter = us_email != null ?
                new ObjectParameter("us_email", us_email) :
                new ObjectParameter("us_email", typeof(string));
    
            var us_phoneParameter = us_phone.HasValue ?
                new ObjectParameter("us_phone", us_phone) :
                new ObjectParameter("us_phone", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("RegistrarUsuario", us_nidParameter, us_passwordParameter, us_nameParameter, us_lastnameParameter, us_emailParameter, us_phoneParameter);
        }
    
        public virtual int UpdateSolistatus(Nullable<decimal> so_id, string soli_status)
        {
            var so_idParameter = so_id.HasValue ?
                new ObjectParameter("so_id", so_id) :
                new ObjectParameter("so_id", typeof(decimal));
    
            var soli_statusParameter = soli_status != null ?
                new ObjectParameter("soli_status", soli_status) :
                new ObjectParameter("soli_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSolistatus", so_idParameter, soli_statusParameter);
        }
    }
}
